version: "2.2"

volumes:
    cmdbuild-db:
    cmdbuild-tomcat:
    cmdbuild-companion:

services:
    cmdbuild-db:
        build:
            context: ..
            dockerfile: src/Dockerfile.postgres
        container_name: cmdbuild-db
        volumes:
            - cmdbuild-db:/var/lib/postgresql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=passw0rd
        restart: always
        mem_limit: 8000m
        mem_reservation: 2000m

    cmdbuild-app:
        build:
            context: ..
            dockerfile: src/Dockerfile.tomcat
        container_name: cmdbuild-app
        links:
           - cmdbuild-db
        depends_on:
           - cmdbuild-db
        ports:
           - 8080:8080 
           - 8443:8443
        restart: always  
        volumes:
            - cmdbuild-tomcat:/usr/local/tomcat
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=passw0rd
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=cmdbuild-db
            - POSTGRES_DB=cmdbuild_3
            - JAVA_OPTS=-Xmx8000m -Xms2000m
        mem_limit: 8000m
        mem_reservation: 2000m

    cmdbuild-companion:
        image: jupyter/datascience-notebook
        container_name: cmdbuild-companion
        links:
           - cmdbuild-app
        depends_on:
           - cmdbuild-app
        ports:
            - 8888:8888
        restart: always
        volumes:
            - cmdbuild-companion:/home/jovyan/work
        environment:
            - JUPYTER_ENABLE_LAB=yes
        mem_limit: 4000m
        mem_reservation: 1000m
