FROM postgres:10.7

ENV POSTGIS_MAJOR 2.5
ENV POSTGRES_USER postgres
ENV POSTGRES_PASS passw0rd

RUN apt-get update && \
      apt-get install -y --no-install-recommends postgresql-10-postgis-$POSTGIS_MAJOR && \
      apt-get install -y --no-install-recommends postgresql-10-postgis-$POSTGIS_MAJOR-scripts && \
      rm -rf /var/lib/apt/lists/*

# cleanup
RUN apt-get -qy autoremove


RUN mkdir -p /docker-entrypoint-initdb.d